Repository D5ng/part2-6team-project, pull requests merged in 2024-03, with the labels that each got.

#60 최신순, 인기순 정렬 안되는 이슈해결, MessageCard, PageCard 리팩토링
  jsconfig.paths.json
  src/components/Card/Card.jsx
  src/components/Card/constant.js
  src/components/CardList/Card.jsx
  src/components/CardList/CardList.jsx
  src/components/CardList/constant.js
  src/components/messageCard/MessageCard.jsx
  src/components/messageCard/MessageCard.style.js
  src/components/messageCard/MessageProfile.jsx
  src/components/paperCard/AddCardButton.jsx
  src/components/paperCard/CardContent.jsx
  src/components/paperCard/ImageGallery.jsx
  src/components/paperCard/PaperCard.jsx
  src/components/paperCard/PaperCard.style.js
  src/components/paperCard/ReactionButton.jsx
  src/hooks/useAsync.js
  src/pages/form/FormCreatePage.jsx
  src/pages/form/components/BackgroundOptions.jsx
  src/pages/form/components/FormSubmitter.jsx
  src/pages/form/components/ImagePickerModal.jsx
  src/pages/form/components/ToggleButton.jsx
  src/pages/form/context/FormContext.jsx
  src/pages/rolling/api.js
  src/pages/rolling/list/RollingList.jsx
  src/pages/rolling/list/components/LatestPaper.jsx
  src/pages/rolling/list/components/PopularPaper.jsx
  src/pages/rolling/paper/components/RollingPaperItem.jsx
  src/utils/backgroundColor.js
Labels: Refactoring

#64 이미지 선택 모달 디자인 및 오타 수정
  public/images/form/unsplash_icon.png
  src/pages/form/api.jsx
  src/pages/form/components/ImagePickerModal.jsx
  src/pages/form/components/ImagePickerModal.style.js
Labels: Refactoring

#65 인기순, 최신순 paper card 누르면 해당 paper로 이동하는 기능 완성
  src/components/paperCard/PaperCard.jsx
  src/components/paperCard/PaperCard.style.js
Labels: Feature

#66 Paper create 페이지에서 이미 존재하는 이름 작성 시 에러메시지 표시 및 버튼 비활성화
  src/components/form/Input.jsx
  src/components/form/Input.style.js
  src/pages/form/api.jsx
  src/pages/form/components/FormSubmitter.jsx
  src/pages/form/context/FormContext.jsx
Labels: Feature

#68 페이퍼 페이지에서 배경이미지 나오게 추가
  src/components/modal/Modal.jsx
  src/hooks/useKeyEvent.js
  src/pages/rolling/paper/components/PaperContents.jsx
  src/pages/rolling/paper/components/PaperContents.style.js
  src/pages/rolling/paper/components/RollingPaperList.jsx
  src/utils/backgroundColor.js
Labels: Feature

#69 OutlinedShareBtn 구조 변경
  src/components/ui/OutlinedComponent.style.js
  src/components/ui/OutlinedShareBtn.jsx
Labels: Refactoring

#70 feat: url공유하기 버튼, kakao공유 버튼 기능 추가
  package-lock.json
  package.json
  src/components/ui/OutlinedShareBtn.jsx
  src/components/ui/Toast.style.js
  src/pages/post/components/KakaoShareButton.jsx
Labels: Feature

#72 레이아웃 관련 hotfix
  src/components/ui/BadgeRelationship.jsx
  src/components/ui/BadgeRelationship.style.js
  src/components/ui/OutlinedComponent.style.js
  src/components/ui/OutlinedShareBtn.jsx
  src/components/ui/Toast.style.js
  src/pages/form/components/ImagePickerModal.jsx
  src/pages/post/Post.jsx
  src/pages/post/PostCreate.jsx
  src/pages/post/components/EmojiChoice.jsx
  src/pages/post/components/EmojiCountBtn.style.js
Labels: Refactoring

#74 Image picker Modal 분리
  src/components/imagePickerModal/ImagePickerModal.jsx
  src/components/imagePickerModal/ImagePickerModalContext.jsx
  src/components/imagePickerModal/api.js
Labels: Refactoring

#73 Remove: 폴더 구조 변경
  jsconfig.paths.json
  src/pages/index.js
  src/pages/list/RollingList.jsx
  src/pages/list/RollingList.style.js
  src/pages/list/api/api.js
  src/pages/list/components/LatestPaper.jsx
  src/pages/list/components/Paper.style.js
  src/pages/list/components/PopularPaper.jsx
  src/pages/list/utils/swiper.breakpoints.js
  src/pages/paper/Paper.jsx
  src/pages/paper/api/index.js
  src/pages/paper/components/PaperContents.jsx
  src/pages/paper/components/PaperContents.style.js
  src/pages/paper/components/RollingPaperItem.jsx
  src/pages/paper/components/RollingPaperItem.style.js
  src/pages/paper/components/RollingPaperList.jsx
  src/pages/paper/components/RollingPaperList.style.js
  src/pages/paper/components/Skeleton.jsx
  src/pages/paper/components/Skeleton.style.js
  src/pages/paper/context/PaperContext.js
  src/pages/paper/hooks/useModal.js
Labels: Rename

#76 분리된 imagePickedMoal 에 맞게 로직 수정
  src/components/imagePickerModal/ImagePickerModal.jsx
  src/components/imagePickerModal/ImagePickerModalContext.jsx
  src/pages/form/FormCreatePage.jsx
  src/pages/form/components/BackgroundOptions.jsx
  src/pages/form/components/FormSubmitter.jsx
  src/pages/form/context/FormContext.jsx
Labels: Refactoring

#75 refactoring: UI모든부분 리팩토링
  src/components/messageCard/MessageProfile.jsx
  src/components/modal/Modal.jsx
  src/components/ui/BadgeEmogi.jsx
  src/components/ui/BadgeRelationship.jsx
  src/components/ui/DeleteButton.jsx
  src/components/ui/OutlinedEmojiBtn.jsx
  src/components/ui/OutlinedShareBtn.jsx
  src/components/ui/PlusIcon.jsx
  src/components/ui/PrimaryCreateBtn.jsx
  src/components/ui/PrimaryLink.jsx
  src/components/ui/Toast.jsx
  src/components/ui/constant.jsx
Labels: Refactoring

#81 Paper Header 리팩토링
  jsconfig.paths.json
  src/Login.jsx
  src/components/PaperHeader/EmojiChoice.jsx
  src/components/PaperHeader/EmojiChoice.style.js
  src/components/PaperHeader/EmojiCountBtn.jsx
  src/components/PaperHeader/EmojiCountBtn.style.js
  src/components/PaperHeader/KakaoShareButton.jsx
  src/components/PaperHeader/MessageCount.jsx
  src/components/PaperHeader/MessageCount.style.js
  src/components/PaperHeader/PaperHeader.jsx
  src/components/PaperHeader/PaperHeader.style.js
  src/components/PaperHeader/TopEmojis.jsx
  src/components/PaperHeader/TopEmojis.style.js
  src/components/PaperHeader/context/PaperHeaderContext.js
  src/components/messageCard/MessageProfile.jsx
  src/components/paperCard/ImageGallery.jsx
  src/components/paperCard/PaperCard.style.js
  src/components/ui/BadgeEmogi.jsx
  src/components/ui/BadgeRelationship.jsx
  src/components/ui/OutlinedComponent.style.js
  src/components/ui/OutlinedEmojiBtn.jsx
  src/components/ui/OutlinedShareBtn.jsx
  src/hooks/useHttp.js
  src/pages/paper/Paper.jsx
  src/pages/paper/api/index.js
  src/pages/post/PostCreate.jsx
  src/pages/post/PostCreate.style.js
  src/pages/post/api/api.jsx
  src/pages/post/components/EmojiCountBtn.jsx
Labels: Refactoring

#83 Paper header 리팩토링 및 reaction 순위 변동 실시간 반영 기능 추가
  src/components/PaperHeader/EmojiChoice.style.js
  src/components/PaperHeader/EmojiCountBtn.jsx
  src/components/PaperHeader/KakaoShareButton.jsx
  src/components/PaperHeader/MessageCount.jsx
  src/components/PaperHeader/MessageCount.style.js
  src/components/PaperHeader/PaperHeader.jsx
  src/components/PaperHeader/PaperHeader.style.js
  src/components/PaperHeader/ReactionModal.jsx
  src/components/PaperHeader/TopEmojis.jsx
  src/components/PaperHeader/ViewReactionsButton.jsx
  src/components/PaperHeader/ViewReactionsButton.style.js
  src/components/PaperHeader/constant.js
  src/components/PaperHeader/context/PaperHeaderContext.js
  src/components/paperCard/PaperCard.jsx
  src/components/paperCard/PaperCard.style.js
  src/components/paperCard/ReactionButton.jsx
  src/components/ui/BadgeEmogi.jsx
  src/components/ui/BadgeEmogi.style.js
  src/components/ui/OutlinedComponent.style.js
  src/components/ui/OutlinedEmojiBtn.jsx
  src/components/ui/OutlinedEmojiButton.jsx
  src/components/ui/OutlinedShareBtn.jsx
Labels: Refactoring, Feature

#89 paper item 드래그 앤 드랍 기능 추가
  package-lock.json
  package.json
  src/pages/paper/components/RollingPaperItem.jsx
  src/pages/paper/components/RollingPaperList.jsx
Labels: Feature

#88 [List page] 색깔 배경 패턴 추가, 스켈레톤 ui 배경 색상 변경
  public/images/card/pattern_beige.svg
  public/images/card/pattern_blue.svg
  public/images/card/pattern_green.svg
  public/images/card/pattern_purple.svg
  src/components/paperCard/PaperCard.jsx
  src/components/paperCard/PaperCard.style.js
  src/pages/list/components/SkeletonUI.style.js
  src/pages/paper/components/PaperContents.jsx
  src/pages/paper/components/PaperContents.style.js
  src/pages/paper/components/RollingPaperItem.style.js
  src/pages/paper/components/RollingPaperList.style.js
  src/utils/backgroundColor.js
Labels: Feature

#92 Create paper form refactoring topic
  package-lock.json
  package.json
  public/images/unsplash/animal.png
  public/images/unsplash/nature.png
  public/images/unsplash/people.png
  public/images/unsplash/space.png
  src/components/form/Input.jsx
  src/components/imagePickerModal/ImagePickerModal.jsx
  src/components/imagePickerModal/ImagePickerModalContext.jsx
  src/components/imagePickerModal/api.js
  src/components/portal/Backdrop.jsx
  src/components/portal/Modal.jsx
  src/components/portal/index.js
  src/components/ui/Loading.jsx
  src/components/unsplashModal/UnsplashCategory.jsx
  src/components/unsplashModal/UnsplashCategory.style.js
  src/components/unsplashModal/UnsplashHeader.jsx
  src/components/unsplashModal/UnsplashHeader.style.js
  src/components/unsplashModal/UnsplashMasonry.jsx
  src/components/unsplashModal/UnsplashMasonry.style.js
  src/components/unsplashModal/UnsplashModal.jsx
  src/components/unsplashModal/UnsplashModal.style.js
  src/components/unsplashModal/UnsplashModalContext.jsx
  src/config/index.js
  src/hooks/useInput.js
  src/hooks/useModal.js
  src/pages/form/FormCreatePage.jsx
  src/pages/form/FormCreatePage.style.js
  src/pages/form/components/BackgroundOptions.jsx
  src/pages/form/components/BackgroundOptions.style.js
  src/pages/form/components/FormSubmitter.jsx
  src/pages/form/components/FormSubmitter.style.js
  src/pages/form/components/ImagePickerModal.jsx
  src/pages/form/components/ImagePickerModal.style.js
  src/pages/form/components/ToggleButton.jsx
  src/pages/form/context/FormContext.jsx
  src/pages/form/hooks/useDefaultBackgroundImage.js
  src/pages/form/reducer/defaultBackgroundImage-reducer.js
  src/pages/form/services/index.js
  src/pages/paper/components/Skeleton.style.js
  src/pages/rolling/messageCreateForm/MessageCreateForm.jsx
  src/pages/rolling/messageCreateForm/components/MessageForm.jsx
  src/reducer/input-reducer.js
  src/service/unplash.js
  src/styles/myReset.js
  src/utils/request-util.js
Labels: Refactoring, Feature

#91 메세지 폼 페이지 기능 추가 및 리펙토링
  src/components/form/Dropdown.jsx
  src/components/unsplashModal/UnsplashModal.jsx
  src/pages/index.js
  src/pages/messageCreateForm/MessageCreateForm.jsx
  src/pages/messageCreateForm/MessageCreateForm.style.js
  src/pages/messageCreateForm/api.jsx
  src/pages/messageCreateForm/components/MessageForm.jsx
  src/pages/messageCreateForm/components/MessageForm.style.js
  src/pages/messageCreateForm/components/PreviewCard.jsx
  src/pages/messageCreateForm/components/PreviewCard.style.js
  src/pages/messageCreateForm/components/PreviewImg.jsx
  src/pages/messageCreateForm/components/PreviewImg.style.js
  src/pages/messageCreateForm/components/ProfileImgList.jsx
  src/pages/messageCreateForm/components/ProfileImgList.style.js
  src/pages/messageCreateForm/components/TextEditor.css
  src/pages/messageCreateForm/components/TextEditor.jsx
  src/pages/rolling/messageCreateForm/MessageCreateForm.jsx
  src/pages/rolling/messageCreateForm/api.jsx
  src/pages/rolling/messageCreateForm/components/MessageForm.jsx
  src/pages/rolling/messageCreateForm/components/PreviewImg.jsx
  src/pages/rolling/messageCreateForm/components/ProfileImgList.jsx
  src/pages/rolling/messageCreateForm/components/TextEditor.jsx
  src/pages/rolling/messageCreateForm/context/MessageFormContext.jsx
  src/service/unplash.js
Labels: Refactoring, Feature

#99 프로필 이미지 미리보기에 기본 이미지 적용 및 PreviewImg, ProfileImgList 쪽 SkeletonUI 적용
  src/pages/messageCreateForm/components/MessageForm.jsx
  src/pages/messageCreateForm/components/ProfileImgList.jsx
  src/pages/messageCreateForm/components/Skeleton.style.js
  src/pages/messageCreateForm/components/SkeletonPreviewImg.jsx
Labels: Feature

#98 Form Create Page 'Recaptcha' 적용
  package-lock.json
  package.json
  src/ReCaptcha.jsx
  src/pages/form/components/FormSubmitter.jsx
Labels: Feature

#96 Config topic
  .env
  public/fonts.css
  public/fonts/NanumBaeEunHyeCe.woff2
  public/fonts/NanumMyeongjo.woff2
  public/fonts/NanumMyeongjoBold.woff2
  public/fonts/NotoSansKR-Bold.woff2
  public/fonts/NotoSansKR-Regular.woff2
  public/fonts/Pretendard-Bold.subset.woff2
  public/fonts/Pretendard-Medium.subset.woff2
  public/fonts/Pretendard-Regular.subset.woff2
  public/fonts/Pretendard-SemiBold.subset.woff2
  public/images/favicon.png
  public/index.html
  src/config/index.js
  src/index.js
  src/pages/messageCreateForm/components/PreviewCard.style.js
  src/service/unplash.js
Labels: SEO

#97 모든 페이지 SEO, react-helmet 적용
  package-lock.json
  package.json
  src/App.js
  src/components/PaperHeader/PaperHeader.jsx
  src/pages/SEOMetaTag.jsx
  src/pages/form/FormCreatePage.jsx
  src/pages/home/Home.jsx
  src/pages/home/Home.style.js
  src/pages/list/RollingList.jsx
  src/pages/messageCreateForm/MessageCreateForm.jsx
  src/pages/paper/Paper.jsx
Labels: SEO

#105 Paper 삭제하기 기능 추가
  public/images/delete-confirm.png
  public/images/icons/delete.svg
  src/components/PaperHeader/PaperHeader.jsx
  src/components/modal/DeleteModal.jsx
  src/components/modal/DeleteModal.style.js
  src/components/ui/BadgeRelationship.style.js
  src/components/ui/DeleteButton.jsx
  src/components/ui/DeleteButton.style.js
  src/components/ui/OutlinedComponent.style.js
  src/components/ui/PrimaryComponent.style.js
  src/components/ui/constant.jsx
  src/pages/form/api.jsx
  src/pages/form/components/FormSubmitter.jsx
  src/pages/form/components/FormSubmitter.style.js
Labels: Feature

#110 message 삭제 기능 추가
  src/components/modal/DeleteModal.jsx
  src/components/modal/Modal.jsx
  src/pages/form/api.jsx
  src/pages/paper/components/RollingPaperList.jsx
  src/reducer/http-reducer.js
Labels: Feature

#119 페이퍼 검색 페이지 추가 및 레이아웃 수정
  src/App.js
  src/components/PaperHeader/PaperHeader.style.js
  src/components/form/Input.jsx
  src/components/form/Input.style.js
  src/components/paperCard/PaperCard.jsx
  src/components/paperCard/PaperCard.style.js
  src/components/ui/DeleteButton.style.js
  src/components/ui/OutlinedComponent.style.js
  src/components/ui/OutlinedEmojiButton.jsx
  src/pages/NotFoundpage/NotFound.style.js
  src/pages/form/components/BackgroundOptions.style.js
  src/pages/form/components/FormSubmitter.style.js
  src/pages/index.js
  src/pages/list/RollingList.jsx
  src/pages/list/RollingList.style.js
  src/pages/list/api/api.js
  src/pages/paper/components/RollingPaperList.jsx
  src/pages/posts/Posts.jsx
  src/pages/posts/Posts.style.js
  src/pages/posts/SkeletonPosts.jsx
  src/pages/posts/SkeletonPosts.style.js
Labels: Feature

#120 카카오톡 공유하기 버튼 Count 추가
  src/components/PaperHeader/KakaoShareButton.jsx
  src/components/PaperHeader/PaperHeader.jsx
  src/components/ui/OutlinedShareBtn.jsx
Labels: Feature

#121 이모티콘 버튼 클릭 함수에 throttling 적용
  src/components/PaperHeader/ReactionModal.jsx
Labels: Feature

#127 모바일 수정사항 수정 및 404페이지 수정
  src/components/PaperHeader/ViewReactionsButton.style.js
  src/components/ui/BadgeEmogi.style.js
  src/components/ui/OutlinedComponent.style.js
  src/pages/NotFoundpage/NotFound.jsx
  src/pages/NotFoundpage/NotFound.style.js
  src/pages/home/Home.style.js
Labels: Refactoring

#131 emoji display refactoring
  src/components/PaperHeader/ViewReactionsButton.jsx
  src/components/PaperHeader/ViewReactionsButton.style.js
  src/components/ui/BadgeEmogi.jsx
  src/components/ui/BadgeEmogi.style.js
Labels: Refactoring

#134 Toast animation 추가
  src/components/paperCard/PaperCard.jsx
  src/components/ui/BadgeEmogi.jsx
  src/components/ui/OutlinedShareBtn.jsx
  src/components/ui/Toast.jsx
  src/components/ui/Toast.style.js
Labels: Feature
